### ISSUE TITLE
Error getting metric PrecPromContRegu

### ISSUE THREAD

**Issue by martimfj** [EquipoAnaliticaXM/API_XM#1]
Hello!

 I'm trying to get the "Precio Promedio Contratos Regulado" But the API is returning that the Metric ID was not found 

post_data = {'MetricId': 'PrecPromContRegu', 'StartDate': '2021-07-18', 'EndDate': '2021-08-17', 'Entity': 'Sistema'}

res =requests.post('<http://servapibi.xm.com.co/daily>', data=post_data) 

res.json() 
> {'Message': 'Id de Métrica no encontrada.'} 

Can someone help me? 
Thank you!

**Comment by martimfj** [comment]
PrecPromContNoRegu (Precio Promedio Contratos No Regulado) metric is also returning the same error.

**Comment by EquipoAnaliticaXM** [comment]
Dear @martimfj, 

Thanks for writing us, we were making an adjustment in both metrics because their natural granularities are hourly.

Best regards,

Equipo de Analítica de XM
