### ISSUE TITLE
pydataxm.ReadDB()

### ISSUE THREAD

**Issue by HectorTH1994** [EquipoAnaliticaXM/API_XM#18]
Hola,
Desde el viernes la api presenta el siguiente error

ConnectionError: HTTPConnectionPool(host='servapibi.xm.com.co', port=80): Max retries exceeded with url: /Lists (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c4a568a3610>: Failed to establish a new connection: [Errno -2] Name or service not known'))

cuando antes funcionaba perfectamente, no he modificado el codigo:

from pydataxm import pydataxm
objetoAPI = pydataxm.ReadDB()

Gracias

**Comment by ljcopsey** [comment]
Hola, sigo recibiendo este error. ¿Podrías compartir cómo lo solucionaste o el problema se resolvió solo? Gracias
