### ISSUE TITLE
Error getting metrics

### ISSUE THREAD

**Issue by martimfj** [EquipoAnaliticaXM/API_XM#2]
Hello,

I'm getting the following error:
`{'Message': 'Id de Métrica no encontrada.'}`

For following metrics:
- CompBolsNaciEner
- CompContEner
- ConsCombAprox
- ConsCombustibleMBTU
- DemaCome
- DemaComeNoReg
- DemaComeReg
- DemaOR
- DesvEner
- DesvMoneda
- DispoCome
- DispoDeclarada
- DispoReal
- EmisionesCH4
- EmisionesCO2
- EmisionesCO2Eq
- EmisionesN2O
- ExcedenteAGPE
- ExpoEner
- Gene
- GeneFueraMerito
- GeneIdea
- GeneProgDesp
- GeneProgRedesp
- GeneSeguridad
- ImpoEner
- MaxPrecOferNal
- PerdidasEner
- PrecBolsNaci
- PrecOferDesp
- PrecPromContNoRegu
- PrecPromContRegu
- RecoNegEner
- RecoNegMoneda
- RecoPosEner
- RecoPosMoneda
- RespComerAGC
- RestAliv
- RestSinAliv
- VentContEner
- factorEmisionCO2e

Code:

```
consult = ReadDB()
collections = json.loads(consult.lectura)
for collection_name, collection_data in collections.items():
    for data in collection_data:
        data_id = data[0]
        try:
            df = consult.request_data(collection_name, data_id, dt.date(2021, 8, 1), dt.date(2021, 9, 12))
            file_name = '_'.join(map(str,data))
            df.to_csv(file_name, index=False)
        except Exception as err:
            print(collection_name, data_id)
```

Are these metrics no longer available, or am I doing something wrong?

Thank you in advance!
- Martim

**Comment by EquipoAnaliticaXM** [comment]
Could you check if your version is updated to 0.2.4?

**Comment by martimfj** [comment]
Hi! Thanks for the fast response.

I found out what was causing the problem. There is a bug on the code, that if I request multiple metrics from different periods (hourly, daily, monthly), the self.url is not modified. My modification was quiet simple.

On each **if** specifying the period:
```
period_base = 'monthly'
self.url = f"http://servapibi.xm.com.co/{period_base}"
```


Another problem is regarding the metric **RespComerAGC**. in the JSON configuration. The Entity is marked as _Recurso_, which returns a 400. Using Entity as Agente, as is specified in the README, it works.


Best regards!
Martim
