### ISSUE TITLE
Demanda en Tiempo Real 

### ISSUE THREAD

**Issue by cervantesjairo** [EquipoAnaliticaXM/API_XM#26]
Buenas,

Estoy intentando usar la API para poder acceder a demanda en tiempo real y el pronostico con la granularidad mostrada aqui https://sinergox.xm.com.co/dmnd/Paginas/Informes/Demanda_Tiempo_Real.aspx

Alguna recomendacion o sugerencia?

Gracias de antemano

Jairo

**Comment by EquipoAnaliticaXM** [comment]
@cervantesjairo, Le indicamos que estas variables no se encuentran disponibles para ser consultadas mediante la API XM u otra funcionalidad, solo pueden descargarse desde el tablero de Power BI disponible en sinergox.
Allí la descarga puede hacerse mediante la funcionalidad de exportar datos:

 
![DemandaTiempoReal](https://github.com/EquipoAnaliticaXM/API_XM/assets/69567089/51c8c7a4-42c3-41b4-b587-5082d5e9429b)


Finalmente compartimos información relevante de las variables:

•	Demanda en tiempo real: Demanda de energía del SIN tomado del Sistema Scada. Unidades en MW y con granularidad de 5 minutos.
•	Pronóstico: Demanda pronosticada por el despacho económico. Unidades en MW y con granularidad de 5 minutos.
