### ISSUE TITLE
[Feature Proposal] Async Client for pydataxm

### ISSUE THREAD

**Issue by jccamargo94** [EquipoAnaliticaXM/API_XM#27]
Hola, EquipoAnaliticaXM. Aprovecho esta oportunidad para agradecer por este wrapper que permite comunicarse con la API de XM mediante Python. Sin duda alguna es un paso más en la dirección correcta con respecto a la disponibilidad de la información

En este issue me gustaría discutir brevemente la posibilidad de tener un cliente asíncrono para la comunicación con la API. Si hay un interés general de la comunidad y la disposición del equipo de analítica para revisar los aportes, podría aportar con una primera versión del cliente asíncrono que podría mejorar significativamente este paquete

# Descripción
Esta funcionalidad expondría un cliente asíncrono `Async Client` que permitiría aprovechar las ventajas de la [programación asíncrona](https://docs.python.org/3/library/asyncio.html) de `Python` para mejorar el desempeño promedio de las solicitudes

# Casos de uso
1. Actualmente cuando se solicita al paquete la información entre fechas que supera los bloques de fecha máximo (_e.g., para información diaria, un máximo de 30 días por solicitud_) la API realiza las peticiones de manera secuanciales por _chunks_ de peticiones; sin embargo, utilizar el asincronismo nos permitiría realizar las peticiones de manera asíncrona, reduciendo así los tiempos de respuesta de manera significativa
2. Cuando se desea solicitar 2 o más métricas con el paquete, incluso si se tiene el código de manera asíncrona, es siempre necesario hacer las peticiones de manera secuencial, por lo cual aportar un cliente asíncrono nos permitiría mejorar dichos desempeños

# Propuesta
-  Implementar una interfaz asíncrona en una clase `Async Client` 
- Con el fin de no reemplazar la actual biblioteca de peticiones no asíncrona (`requests`) crearíamos dependencias opcionales para la instalación del cliente asíncrono: Propongo que podría ser `pydataxm[async]` 
- Para la biblioteca de peticiones asíncronas propongo que podríamos usar [aiohttp](https://pypi.org/project/aiohttp/) o [httpx](https://pypi.org/project/httpx/)

# Modo de uso
Este sería un modo de uso para el cliente asíncrono usando un script sencillo llamado `async_pydataxm.py`
```[python]
from asyncio import gather, run
from datetime import date

from pydataxm import AsyncClient

async_API = AsyncClient()


async def async_mode_pydataxm():
    "This coroutine fetch data in async mode"
    requested_data_1 = async_API.request_data(
        metric="DemaReal",
        entity="Sistema",
        start_date=date(2024,1,1),
        end_date=date(2024,1,23),
        filters=[],
    )
    requested_data_2 = async_API.request_data(
        metric="DemaCome",
        entity="Sistema",
        start_date=date(2024,1,1),
        end_date=date(2024,1,23),
        filters=[],
    )
    return await gather(*[requested_data_1, requested_data_2])

run(async_mode_pydataxm())

```

**Comment by EquipoAnaliticaXM** [comment]
Buenos días, @jccamargo94.

Agradecemos mucho tu sugerencia. Al respecto le informamos que en la versión 0.3.8 de la API ya hemos implementado la librería propuesta (asyncio). Puedes encontrar más detalles en el código fuente a través del siguiente enlace: [GitHub - pydataxm.py.](https://github.com/EquipoAnaliticaXM/API_XM/blob/master/pydataxm/pydataxm.py)

**Comment by jccamargo94** [comment]
> Buenos días, @jccamargo94.
> 
> Agradecemos mucho tu sugerencia. Al respecto le informamos que en la versión 0.3.8 de la API ya hemos implementado la librería propuesta (asyncio). Puedes encontrar más detalles en el código fuente a través del siguiente enlace: [GitHub - pydataxm.py.](https://github.com/EquipoAnaliticaXM/API_XM/blob/master/pydataxm/pydataxm.py)

Muchas gracias por la respuesta. Que bien saber que este wrapper sigue en desarrollo y cada vez mejora más. Gracias

**Comment by jccamargo94** [comment]
> Buenos días, @jccamargo94.
> 
> Agradecemos mucho tu sugerencia. Al respecto le informamos que en la versión 0.3.8 de la API ya hemos implementado la librería propuesta (asyncio). Puedes encontrar más detalles en el código fuente a través del siguiente enlace: [GitHub - pydataxm.py.](https://github.com/EquipoAnaliticaXM/API_XM/blob/master/pydataxm/pydataxm.py)

Muchas gracias por la respuesta. Que bien saber que este wrapper sigue en desarrollo y cada vez mejora más. Gracias
