### ISSUE TITLE
Error en librería

### ISSUE THREAD

**Issue by jcastrog1** [EquipoAnaliticaXM/API_XM#3]
Para un algoritmo de predicción basado en ML estuve tratando de acceder a la API. Quisiera reportarles un error. Cuando se hace request de uno de los listados (ejemplo: ListadoMetricas), la url dentro de la librería es 'http://servapibi.xm.com.co/{period_base}'. Sin embargo, dentro de la función de request utiliza un replace('hourly','lists'). Esto es un error ya que la URL previa no tenía 'hourly', y por tanto arroja un json vacío.

Ya lo solucione internamente, pero quizás es bueno mejorarlo en la próxima versión.

Gracias por la herramienta.

**Comment by EquipoAnaliticaXM** [comment]
Gracias por el aviso @jcastrog1, estaremos atentos a cualquier comentario.
