### ISSUE TITLE
Error obteniendo una metrica: TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by FaSaSu20** [EquipoAnaliticaXM/API_XM#4]
Estoy tratando de ejecutar el codido de "data_visualization.ipynb" y obtengo el siguiente error:

![image](https://user-images.githubusercontent.com/65478386/180091333-5f02a873-02e9-4846-8a3e-26cdd32222da.png)

**Comment by EquipoAnaliticaXM** [comment]
Hola,  @FaSaSu20 muchas gracias por escribirnos.

Para generar mayor claridad, hemos actualizado un archivo denominado requeriments.yml con el entorno que corre adecuadamente el libro que usted desea reproducir. Por favor instalar el entorno especificado y nos da su aviso para dar por cerrado el caso.

**Comment by FaSaSu20** [comment]
Ya logré correr el Notebook con el entorno indicado, muchas gracias.
