### ISSUE TITLE
Error acceso al servidor

### ISSUE THREAD

**Issue by vlady8711** [EquipoAnaliticaXM/API_XM#6]
Buenas tardes,

Desde hace una semana se me está presentando un error al tratar de conectarme a la BD. Intenté ejecutar los ejemplos de la API y también me generan el mismo error, entonces quisiera consultarles si hay alguna novedad con el servidor. El error se presenta al ejecutar la instrucción:

objetoAPI = pydataxm.ReadDB() 

y el error es :
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Quedo atento, mil gracias.

**Comment by EquipoAnaliticaXM** [comment]
Se han realizado validaciones al microservicio que han eliminado la intermitencia que veníamos presentando, agradecemos su atención y quedamos atentos si surgen nuevas inquietudes
