### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by zibatech** [EquipoAnaliticaXM/API_XM#7]
El servidor no se encuentra disponible, regresando un error con código HTTP 503, atribuido a errores donde un servicio web opera correctamente, pero no puede maniobrar una petición en tiempo real.

**Comment by EquipoAnaliticaXM** [comment]
Podrían por favor compartirnos imagen del error que les presenta?

**Comment by jmendez-enersinc** [comment]
![image](https://user-images.githubusercontent.com/98413023/203106555-3b53fac2-a03b-4587-8882-533ac8097043.png)

En algunas ocasiones responde correctamente, pero en otras arroja este mensaje o el error http 503. Presenta  aun mas intermitencia realizando peticiones desde servicios en la nube ubicados en us-central.
