### ISSUE TITLE
INFORMACIÓN NO SINCRONIZADA CON LA PAGINA

### ISSUE THREAD

**Issue by zibatech** [EquipoAnaliticaXM/API_XM#8]
Espero estén bien primero que todo y de antemano agradecerles por el servicio, me parece una idea bastante útil, pero tenía una observación referente a la información que se expone, ya que esta no se encuentra sincronizada con la información que se muestra en la página de XM, o al menos en el caso de [generación del despacho nacional](https://www.xm.com.co/generaci%C3%B3n/informes-despacho/despacho-nacional).

Quería dejarles saber que desde los lineamientos como servicio _Open Source_, pueden contar con cualquier _feedback_ o ayuda por nuestra parte.

Muchas gracias.

**Comment by EquipoAnaliticaXM** [comment]
Agradecemos sus comentarios, nos encontramos validando la forma cómo podemos ampliar nuestra API a otras variables del mercado y la operación. Seguiremos informando nuevas actualizaciones y estaremos en contacto. ¡Saludos!
