### ISSUE TITLE
Formato de la hora

### ISSUE THREAD

**Issue by lav-julien** [EquipoAnaliticaXM/API_XM#9]
Cual es el formato utilizado para la hora?
Es la hora "Values_Hour01" del dia 2022_12_22 las doce de la noche en Colombia y la hora "Values_Hour24" las once de la noche? O es el formate diferente?
Muchas gracias

**Comment by EquipoAnaliticaXM** [comment]
Buen día, 
Si, así como indicas la hora "Values_Hour01" corresponde a la hora 00:00 y las "Values_Hour24" corresponde a las 23:00.
Saludos
